# Generated by Django 2.2.7 on 2019-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_full_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
